info:
  title: Taskboard Queries API
  version: 0.1.0
swagger: '2.0'
basePath: /api
consumes:
  - application/json
produces:
  - application/json
paths:
  /lists:
    get:
      operationId: GetLists
      description:
        'Gets all lists'
      responses:
        '200':
          description: All lists
          schema:
            type: array
            items:
              $ref: '#/definitions/List'
  /list/{id}:
    get:
      operationId: GetList
      description:
        'Gets a list'
      responses:
        '200':
          description: The list
          schema:
            $ref: '#/definitions/List'
      parameters:
        - name: id
          in: path
          required: true
          type: string
  /list/{listid}/task/{taskid}:
    get:
      operationId: GetTask
      description:
        'Gets a task'
      responses:
        '200':
          description: The task
          schema:
            $ref: '#/definitions/Task'
      parameters:
        - name: listid
          in: path
          required: true
          type: string
        - name: taskid
          in: path
          required: true
          type: string
definitions:
  List:
    type: object
    properties:
      id:
        type: string
      name:
        type: string
      tasks:
        type: array
        items: 
          $ref: '#/definitions/Task'
    required:
      - id
      - name
  Task:
    type: object
    properties:
      id:
        type: string
      name:
        type: string
      description:
        type: string
    required:
      - id
      - name
      - description