apiVersion: apps/v1
kind: Deployment
metadata:
  name: commands-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: commands
  template:
    metadata:
      labels:
        app: commands
    spec:
      containers:
      - name: commands
        image: scottrangerio.azurecr.io/taskboard-commands:1.0
        ports:
        - containerPort: 80
        env:
        - name: AI_INSTRUMENTATIONKEY
          valueFrom:
            secretKeyRef:
              name: ai-settings
              key: instrumentation-key
        - name: COSMOS_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: cosmos-settings
              key: endpoint
        - name: COSMOS_KEY
          valueFrom:
            secretKeyRef:
              name: cosmos-settings
              key: master-key
        - name: COSMOS_DB
          valueFrom:
            secretKeyRef:
              name: cosmos-settings
              key: db
        - name: COSMOS_COLLECTION
          valueFrom:
            secretKeyRef:
              name: cosmos-settings
              key: collection
        - name: LIST_RESOURCE_URI
          value: https://taskboard-srio-apim.azure-api.net/list/{0}
        - name: TASK_RESOURCE_URI
          value: https://taskboard-srio-apim.azure-api.net/list/{0}/task/{1}
      imagePullSecrets:
      - name: azure